stages:
  - containerization
  - deployment

variables:
  APPLICATION_NAME: homepage
  CONTAINER_REGISTRY: localhost:5000
  CERTIFICATE_DOMAIN: maximemoreillon.com

containerization:
  stage: containerization
  script:
    - docker build -t ${CONTAINER_REGISTRY}/${APPLICATION_NAME} .
    - docker push ${CONTAINER_REGISTRY}/${APPLICATION_NAME}

deployment:
  stage: deployment
  script:
    - envsubst < deployment.yml | kubectl apply -f -
    - kubectl rollout restart deployment/${APPLICATION_NAME}
  environment:
    name: staging
    kubernetes:
      namespace: moreillon
