apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      labels:
        app: homepage
    spec:

      containers:
      - name: homepage
        image: localhost:32000/homepage
        imagePullPolicy: Always
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: homepage
spec:
  ports:
  - port: 80
  selector:
    app: homepage # Name of the service
  type: ClusterIP
---
# prod_issuer.yaml
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer # Maybe could make it just an issuer for individual apps
metadata:
  name: homepage-letsencrypt
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: m.moreillon@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: homepage-letsencrypt
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class:  nginx
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: homepage # Name of the ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "homepage-letsencrypt"
spec:
  tls:
  - hosts:
    - maximemoreillon.com
    secretName: homepage-letsencrypt
  rules:
  - host: maximemoreillon.com
    http:
      paths:
      - path: /
        backend:
          serviceName: homepage # Name of the service
          servicePort: 80
