export default [
  {
    icon: "mdi:newspaper",
    label: "Articles",
    url: "https://cms.maximemoreillon.com",
    category: "Software",
  },
  {
    icon: "mdi:tools",
    label: "Projects",
    url: "https://articles.maximemoreillon.com/articles?tag_id=111",
    category: "Software",
  },
  {
    icon: "simple-icons:medium",
    label: "Medium",
    url: "https://moreillon.medium.com/",
    category: "Software",
  },
  {
    icon: "mdi:facebook",
    label: "Facebook",
    url: "https://www.facebook.com/maxime.moreillon",
    category: "Social media",
  },
  {
    icon: "mdi:twitter",
    label: "Twitter",
    url: "https://twitter.com/m_moreillon",
    category: "Social media",
  },
  {
    icon: "mdi:instagram",
    label: "Instagram",
    url: "https://www.instagram.com/maxime_moreillon/",
    category: "Social media",
  },
  {
    icon: "mdi:youtube",
    label: "YouTube",
    url: "https://www.youtube.com/channel/UCvk0FMjKbin0FGU9LPe-T_g",
    category: "Social media",
  },
  {
    icon: "mdi:docker",
    label: "Docker Hub",
    url: "https://hub.docker.com/u/moreillon",
    category: "Software",
  },
  {
    icon: "mdi:github",
    label: "GitHub",
    url: "https://github.com/maximemoreillon",
    category: "Software",
  },
  // {
  //   icon: "mdi:gitlab",
  //   label: "GitLab",
  //   url: "https://gitlab.com/moreillon",
  //   category: "Software",
  // },
  {
    icon: "mdi:npm",
    label: "NPM",
    url: "https://www.npmjs.com/~moreillon",
    category: "Software",
  },
  {
    icon: "simple-icons:artifacthub",
    label: "Artifact Hub",
    url: "https://artifacthub.io/packages/search?user=moreillon",
    category: "Software",
  },
  {
    icon: "simple-icons:googlescholar",
    label: "Google Scholar",
    url: "https://scholar.google.com/citations?user=0gkCupAAAAAJ",
    category: "Work",
  },
  {
    icon: "mdi:linkedin",
    label: "LinkedIn",
    url: "https://www.linkedin.com/in/maxime-moreillon",
    category: "Work",
  },
  {
    icon: "mdi:license",
    label: "Patents",
    url: "https://patents.google.com/?inventor=Maxime+MOREILLON",
    category: "Work",
  },
  // {
  //   icon: "mdi:tools",
  //   label: "Projects",
  //   url: "https://articles.maximemoreillon.com/articles?tag_id=111",
  //   category: "Mechatronics",
  // },
  // {
  //   image: "images/oshwlab.png",
  //   label: "OSHWLab",
  //   url: "https://oshwlab.com/m.moreillon",
  //   category: "Mechatronics",
  // },
  {
    icon: "simple-icons:thingiverse",
    label: "Thingiverse",
    url: "https://www.thingiverse.com/moreillon/designs",
    category: "Mechatronics",
  },
  {
    icon: "mdi:account",
    label: "Modeling profile",
    url: "https://modeling.maximemoreillon.com",
    category: "Modeling",
  },
  {
    icon: "mdi:instagram",
    label: "Instagram (Modeling)",
    url: "https://www.instagram.com/maxime_moreillon_modeling",
    category: "Modeling",
  },
  {
    icon: "azs",
    label: "AZS entertainment",
    url: "https://azs-group.jp/manage_post/990",
    category: "Modeling",
  },
]
